export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const FETCH_BACKLOG_REQUEST = 'FETCH_BACKLOG_REQUEST';
export const FETCH_BACKLOG_SUCCESS = 'FETCH_BACKLOG_SUCCESS';
export const FETCH_BACKLOG_FAILURE = 'FETCH_BACKLOG_FAILURE';

export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';
